sudo: false
language: ruby
cache: bundler
install:
  # If we're running for a pull request, check out the revision of sass-spec
  # referenced by that pull request.
  - if-pr() { if [ ! -z "$TRAVIS_PULL_REQUEST" -a "$TRAVIS_PULL_REQUEST" != false ]; then "$@"; fi }
  - if-pr mkdir sass-spec
  - if-pr git -C sass-spec init
  - if-pr git -C sass-spec pull --depth=1 git://github.com/sass/sass-spec `extra/sass-spec-ref.sh`
  - if-pr bundle config local.sass-spec "`pwd`/sass-spec"

  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle update sass-spec
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.0
gemfile: Gemfile
env:
  - MATHN=true RUBOCOP=false
  - MATHN=false RUBOCOP=false
branches:
  only:
    - master
    - stable
    - stable_3_2
    - next
notifications:
  irc: {channels: "irc.freenode.org#sass"}
matrix:
  include:
    - rvm: 2.2.3
      env: MATHN=true RUBOCOP=true
    - rvm: 2.1.7
      env: MATHN=true RUBOCOP=true
    - rvm: 2.0.0
      env: MATHN=true RUBOCOP=true

