rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - ree
gemfile: Gemfile
env:
  - MATHN=true RUBOCOP=false
  - MATHN=false RUBOCOP=false
branches:
  only:
    - master
    - stable
notifications:
  irc: {channels: "irc.freenode.org#sass"}
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-18mode
    - rvm: jruby-19mode
  include:
    - rvm: 2.0.0
      env: MATHN=true RUBOCOP=true
    - rvm: 1.9.3
      env: MATHN=true RUBOCOP=true
